todo-pr-checker:
  # When should comments be posted? 
  post_comment: 'items_found'
  # Files that get matched by any of these regular expressions will be ignored
  ignore_regex: ['validation/']
  # What action items should be looked for (setting this will the overwrite default values)
  action_items: ['TODO', 'FIXME', 'BUG']
  # Languages/file types to add. At least either the line comment or both block comment definitions are required.
  # If there are no line comments in the language, you may set the value to null.
  add_languages: [
    ['js', '//', '/*', '*/'],
    ['css', null, '/*', '*/'],
    ['.py', '#']
  ]
  # Whether or not searching for action items should be case sensitive
  case_sensitive: false
  # If multiline comments should also be searched for action items
  # This may result in some false positives or negatives if the opening or closing lines of a comment are not in the diff 
  enable_multiline_comments: false