AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 300

Layout/EndOfLine:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false
